[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm install -g @nestjs/cli",
  "cd backend && npm install --legacy-peer-deps",
  "cd frontend && npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm run start:prod"

[variables]
NODE_ENV = "production"
